baseurl = "https://wabbitspunch.netlify.app/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "WabbitsPunch"
theme = "ramium"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
pluralizeListTitles = false
disqusShortname = ""
googleAnalytics = "UA-73417314-20"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

buildFuture = true
rssLimit = 10

[permalinks]
    posts = "/posts/:slug/"

[params]
    description = "Rでもにょる自然言語処理"
    author = "paithiov909"
    images = ["images/wabbits.jpg"]

    googleSearch = "000195935875495954044:0i-nojmdwds"

    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page

    githubProfile = "paithiov909/wabbitspunch/"

    tagsInHome = 0  # set zero to not show in home page
    sectionsInHome = 10  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 5

[taxonomies]
    tag = "tags"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/articles/about/"
        weight = 2
    [[menu.main]]
        name = "Info"
        url = "/articles/env/"
        weight = 3
    [[menu.main]]
        name = "Twitter"
        url = "https://twitter.com/paithiov909"
        weight = 4
