baseurl = "https://wabbitspunch.netlify.app/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "WabbitsPunch"
theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableGitInfo = true
googleAnalytics = "UA-73417314-20"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

rssLimit = 10

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    subTitle = "Rでもにょる自然言語処理"
    description = "Rでテキストマイニング的な何か"

    images = ["img/wabbits.png"]

    mainSections = ["post"]
    license = "MIT license"
    licenseLink = "https://github.com/paithiov909/wabbitspunch/blob/master/LICENSE"

[taxonomies]
    tag = "tags"

[markup]
    [markup.highlight]
        style = "monokailight"
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 2

[menu]
    [[menu.nav]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.nav]]
        name = "About"
        url = "/about/"
        weight = 2

    [[menu.link]]
        name = "GitHub"
        url = "https://github.com/paithiov909/wabbitspunch"
        weight = 1
    [[menu.link]]
        name = "Twitter"
        url = "https://twitter.com/paithiov909"
        weight = 2
