baseurl = "https://wabbitspunch.netlify.app/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "WabbitsPunch"
theme = "hugo-lithium"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
pluralizeListTitles = false
googleAnalytics = "UA-73417314-20"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

rssLimit = 10

[permalinks]
    posts = "/posts/:slug/"

[params]
    description = "Rでもにょる自然言語処理"

    highlightjsVersion = "9.18.0"
    highlightjsCDN = "https://cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "js"]
    highlightjsTheme = "github"

    favicon = "images/favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[taxonomies]
    tag = "tags"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2
    [[menu.main]]
        name = "Twitter"
        url = "https://twitter.com/paithiov909"
        weight = 3
